### ISSUE TITLE
JWT Malformed Error While Setting up @slack/oauth

### ISSUE THREAD

**Issue by jasonwu2153** [slackapi/node-slack-sdk#1150]
### JWT Malformed Error While Setting up `@slack/oauth`

I'm trying to set up a slack installation endpoint as a redirect uri using `@slack/oauth`. I have an endpoint handler on my server that looks like this:

```
handleOauthRedirect: async (req: Request, res: Response) => {
        slackInstaller.handleCallback(req, res);
}
```

### The installation URL I'm Using
https://slack.com/oauth/v2/authorize?...redirect_uri=my-slack-install-endpoint

### The error I get
```
[ERROR]  OAuth:InstallProvider:0 JsonWebTokenError: jwt malformed
    at Object.module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:63:17)
    at ClearStateStore.<anonymous> (/app/node_modules/@slack/oauth/dist/index.js:412:42)
    at step (/app/node_modules/@slack/oauth/dist/index.js:44:23)
    at Object.next (/app/node_modules/@slack/oauth/dist/index.js:25:53)
    at /app/node_modules/@slack/oauth/dist/index.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/@slack/oauth/dist/index.js:15:12)
    at ClearStateStore.verifyStateParam (/app/node_modules/@slack/oauth/dist/index.js:409:16)
    ...
```

I tried looking for solutions online and noticed this seemed to have been reported for a [user using bolt-js](https://github.com/slackapi/bolt-js/issues/577). The solution was to use bolt's generated authorize URL endpoint, but I'm not using bolt-js. 

The state parameter I pass into the url matches the `stateSecret` in the installation, so I'm not sure what's going on here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [x] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by jasonwu2153** [comment]
Very silly mistake on my part. I was passing in the state secret in the state param instead of the actual generated state. Everything works now 🙌
