### ISSUE TITLE
Why get user list missing_scope

### ISSUE THREAD

**Issue by JinYuSha0** [slackapi/node-slack-sdk#1361]
I want to use sdk to get user list

```javascript
 const client = await new WebClient('my-token');  // I don't know if this token is the accessToken for user login
 const list = await client.users.list();
```

Then I got this error

```javascript
Error: An API error occurred: missing_scope
    at Object.platformErrorFromResult (E:\MyProject\aui-i18-admin\node_modules\@slack\web-api\src\errors.ts:94:5)
    at WebClient.apiCall (E:\MyProject\aui-i18-admin\node_modules\@slack\web-api\src\WebClient.ts:198:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at SlackResolver.usersList (E:\MyProject\aui-i18-admin\src\server\modules\slack\slack.resolver.ts:44:20)
    at target (E:\MyProject\aui-i18-admin\node_modules\@nestjs\core\helpers\external-context-creator.js:77:28)
    at E:\MyProject\aui-i18-admin\node_modules\@nestjs\core\helpers\external-proxy.js:9:24 {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'missing_scope',
    needed: 'users:read',
    provided: 'identity.basic,identity.email,identity.avatar,identity.team,openid,email,profile',
    response_metadata: { scopes: [Array], acceptedScopes: [Array] }
  }
}
```

I try to add User Token Scopes in OAuth & Permissions

![image](https://user-images.githubusercontent.com/20939091/138390388-36d20a1a-13e3-4341-9061-91cf08f001c6.png)

Then reinstall workspace, Then I encountered another problem

![image](https://user-images.githubusercontent.com/20939091/138390497-5fcfacde-17fd-4491-8eb5-bade71939153.png)

Unable to install  (Invaild_scope)

And now I can't find the reinstall button

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

### Reproducible in:

```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack
node --version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version

(Paste the output of 
```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack
```
or refer to your `package.json`)

#### Python runtime version

(Paste the output of `node --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)

1.
2.
3.

### Expected result:

(Tell what you expected to happen)

### Actual result:

(Tell what actually happened with logs, screenshots)

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @JinYuSha0, thanks for writing in!

> identity.basic,identity.email,identity.avatar,identity.team,openid,email,profile

These are ["Sign in with Slack" (SIWS) feature](https://api.slack.com/authentication/sign-in-with-slack) related scopes. Unfortunately, when you run an OAuth flow with SIWS scopes, other scopes such as `users:read` are not allowed in the same OAuth flow. The SIWS flow is supposed to be used only for verifying a person's identity using his/her/their Slack account. Acquiring other scopes for making effects inside the person's Slack workspace needs to be done separately.

Thus, your app can initiate a different OAuth flow to ask your end-users to give `users:read` permission to your app. At the end of the day, your app can have two URLs to start the OAuth flows -- 1) for "Sign in with Slack" 2) for enabling the app to access Slack workspace information.

I hope this was helpful to you. If everything is clear now, would you mind closing this question issue?
