### ISSUE TITLE
Unhandled state machine events

### ISSUE THREAD

**Issue by hankjacobs** [slackapi/node-slack-sdk#1471]
#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [X] `@slack/socket-mode`
- [ ] I don't know

#### The Slack SDK version

3.11.0

#### Node.js runtime version

v17.9.0

#### OS info

Ubuntu 18.04.6 LTS

#### Steps to reproduce:

1. run socket mode app for extended period of time

### Expected result:

an error is not thrown

### Actual result:

The following "Unhandled event" errors are thrown occasional (on the order of days):
```
Error: Unhandled event 'server disconnect old socket' in state 'connected'.
  at finity.lib.core:StateMachine.StateMachine.handleUnhandledEvent(/apps/app/node_modules/finity/lib/core/StateMachine.js:76:13)
  at finity.lib.core:HierarchicalStateMachine.null.<anonymous>(/apps/app/node_modules/finity/lib/core/HierarchicalStateMachine.js:79:33)
  at finity.lib.core:TaskScheduler.TaskScheduler.execute(/apps/app/node_modules/finity/lib/core/TaskScheduler.js:29:7)
  at finity.lib.core:TaskScheduler.TaskScheduler.enqueue(/apps/app/node_modules/finity/lib/core/TaskScheduler.js:19:12)
  at finity.lib.core:HierarchicalStateMachine.HierarchicalStateMachine.handle(/apps/app/node_modules/finity/lib/core/HierarchicalStateMachine.js:72:24)
  at @slack.socket-mode.dist:SocketModeClient.SocketModeClient.onWebSocketMessage(/apps/app/node_modules/@slack/socket-mode/dist/SocketModeClient.js:465:31)
  at ws.lib:event-target.WebSocket.onMessage(/apps/app/node_modules/ws/lib/event-target.js:132:16)
  at node:events.WebSocket.emit(node:events:527:28)
  at node:domain.WebSocket.emit(node:domain:475:12)
  at ws.lib:websocket.Receiver.receiverOnMessage(/apps/app/node_modules/ws/lib/websocket.js:1047:20)
  ```

This one seems to happen every 6 days or so:
```
Error: Unhandled event 'websocket close' in state 'refreshing-connection'.
  at finity.lib.core:StateMachine.StateMachine.handleUnhandledEvent(/apps/app/node_modules/finity/lib/core/StateMachine.js:76:13)
  at finity.lib.core:HierarchicalStateMachine.null.<anonymous>(/apps/app/node_modules/finity/lib/core/HierarchicalStateMachine.js:79:33)
  at finity.lib.core:TaskScheduler.TaskScheduler.execute(/apps/app/node_modules/finity/lib/core/TaskScheduler.js:29:7)
  at finity.lib.core:TaskScheduler.TaskScheduler.enqueue(/apps/app/node_modules/finity/lib/core/TaskScheduler.js:19:12)
  at finity.lib.core:HierarchicalStateMachine.HierarchicalStateMachine.handle(/apps/app/node_modules/finity/lib/core/HierarchicalStateMachine.js:72:24)
  at @slack.socket-mode.dist:SocketModeClient.WebSocket.<anonymous>(/apps/app/node_modules/@slack/socket-mode/dist/SocketModeClient.js:381:76)
  at ws.lib:event-target.WebSocket.onClose(/apps/app/node_modules/ws/lib/event-target.js:136:16)
  at node:events.WebSocket.emit(node:events:527:28)
  at node:domain.WebSocket.emit(node:domain:475:12)
  at ws.lib:websocket.WebSocket.emitClose(/apps/app/node_modules/ws/lib/websocket.js:246:10)
  ```

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @hankjacobs, thanks for taking the time to report this issue. 

We are going to make a new minor version v1.3.0 and I am confident that the new version resolves this issue. If you have a chance, trying the RC version out and sharing your feedback (if any) would be appreciated. https://www.npmjs.com/package/@slack/socket-mode/v/1.3.0-rc.1

**Comment by hankjacobs** [comment]
Thanks! I'll keep an eye out for the new version and try to test with the RC in the mean time.
