### ISSUE TITLE
socket-mode: explicit server disconnect during 'connecting' state not handled

### ISSUE THREAD

**Issue by filmaj** [slackapi/node-slack-sdk#1787]
@filmaj I seem to be hitting the following now on 1.3.5:

```
[INFO]  socket-mode:SocketModeClient:0 Going to establish a new connection to Slack ...
/home/patrick/slack/node_modules/finity/lib/core/StateMachine.js:76
      throw new Error('Unhandled event \'' + event + '\' in state \'' + this.currentState + '\'.');
            ^

Error: Unhandled event 'server explicit disconnect' in state 'connecting'.
    at StateMachine.handleUnhandledEvent (/home/patrick/slack/node_modules/finity/lib/core/StateMachine.js:76:13)
    at /home/patrick/slack/node_modules/finity/lib/core/HierarchicalStateMachine.js:79:33
    at TaskScheduler.execute (/home/patrick/slack/node_modules/finity/lib/core/TaskScheduler.js:29:7)
    at TaskScheduler.enqueue (/home/patrick/slack/node_modules/finity/lib/core/TaskScheduler.js:19:12)
    at HierarchicalStateMachine.handle (/home/patrick/slack/node_modules/finity/lib/core/HierarchicalStateMachine.js:72:24)
    at SocketModeClient.onWebSocketMessage (/home/patrick/slack/node_modules/@slack/socket-mode/dist/SocketModeClient.js:608:31)
    at WebSocket.onMessage (/home/patrick/slack/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:518:28)
    at Receiver.receiverOnMessage (/home/patrick/slack/node_modules/ws/lib/websocket.js:1068:20)
    at Receiver.emit (node:events:518:28)
```

With debug logging it shows:

```
[DEBUG]  socket-mode:SocketModeClient:0 Received a message on the WebSocket: {"type":"disconnect","reason":"too_many_websockets","debug_info":{"host":"applink-2"}}
[DEBUG]  socket-mode:SocketModeClient:0 Received "disconnect" (reason: too_many_websockets) message - will attempt reconnect
```

_Originally posted by @MadrMan in https://github.com/slackapi/node-slack-sdk/issues/1654#issuecomment-2094100237_

**Comment by filmaj** [comment]
This is a tricky issue to handle, because the 1.x line of socket-mode's architecture is such that there is a _single_ state machine to handle transitions, but potentially, during a reconnect, _two_ WebSocket connections are briefly active/overlapping as a connection is re-established. The underlying problem is, during this reconnect when we have two WS connections open, each WebSocket connection pumps events into the single state machine, causing unexpected state transitions.

Consider the case where, at more or less the same time, one WS connection sends a "disconnect" event to the state machine and another sends a "open" or "connected" event. The single state machine will get confused.

This issue is resolved in socket-mode 2.x, as the architecture has completely changed. Socket-mode 2.0 is available in [bolt 4.0.0 rc1](https://www.npmjs.com/package/@slack/bolt/v/4.0.0-rc.1), and has been used successfully by some customers who have adopted it early.

**Comment by filmaj** [comment]
The first log is a big clue:

> 2024-09-03 02:38:31.605	A pong wasn't received from the server before the timeout of 5000ms!

This is not a good sign, and may actually point to an issue in the Slack backend; under the hood, socket-mode sends [`ping` messages to the Slack backend as a kind of heartbeat, to ensure the connection is working properly. The fact that Slack did not respond with the per-specification `pong` message](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#pings_and_pongs_the_heartbeat_of_websockets) within 5 seconds is unexpected and unusual.

**Comment by weijiany** [comment]
Hi @filmaj do you have a plan to release the stable 4.x version? I want to determine whether we upgrade to rc1 or wait the stable version.

**Comment by filmaj** [comment]
@weijiany do you mean a bolt-js v4 release? We have started to put together plans for it but there is no specific timeline. If this issue is affecting you, I recommend trying the v4 rc.

**Comment by zimeg** [comment]
> This issue is resolved in socket-mode 2.x, as the architecture has completely changed.

👋 I'll close this issue with an understanding of our latest releases of both `@slack/socket-mode` and `@slack/bolt` use patterns of WebSocket events to communicate instead of a state machine.

Those are quite impressive changes I think have been stable for some time now 🧠 ✨

- https://www.npmjs.com/package/@slack/bolt?activeTab=versions
- https://www.npmjs.com/package/@slack/socket-mode?activeTab=versions
