### ISSUE TITLE
"Basic Usage" webhook example doesn't run

### ISSUE THREAD

**Issue by mjbrender** [slackapi/node-slack-sdk#290]
Hey peeps 👋 

* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
First example in "Slack Developer Kit for Node.js" does not run: 

```js
$ node webhook.js
/Users/mjbrende/Documents/Develop/hellobot/nodesdk/webhook.js:12
});
 ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

#### Reproducible in:

OS version(s): MacOS 10.12.1 (16B2555)
Device(s): Macbook Pro

#### Steps to reproduce:

1. Take example from the docs 
2. export SLACK_WEBHOOK_URL for my Slack app
3. Run file

### Expected result:

Errors instead of runs

### Actual result:

Error message above

### Notes 

I'm glad to open a PR to help, just don't know node well enough to correct the issue.

**Comment by DEGoodmanWilson** [comment]
:bow: Thanks for this!
