### ISSUE TITLE
apiCb is not a function

### ISSUE THREAD

**Issue by matthewdias** [slackapi/node-slack-sdk#338]
with
```
    slack.chat.unfurl(token, channel, message_ts, {
      [link.url]: { text: "blah" }
    }, (err, info) => {
      if (err)
        throw new Error(err)
      console.log(info)
    })
```
i get 
```
error: invalid_auth
2017-04-27T09:28:41.166746+00:00 app[web.1]: error:  TypeError: apiCb is not a function
2017-04-27T09:28:41.166747+00:00 app[web.1]:     at handleHttpResponse (/app/node_modules/@slack/client/lib/clients/transports/call-transport.js:118:5)
2017-04-27T09:28:41.166747+00:00 app[web.1]:     at handleTransportResponse (/app/node_modules/@slack/client/lib/clients/transports/call-transport.js:155:19)
2017-04-27T09:28:41.166748+00:00 app[web.1]:     at apply (/app/node_modules/lodash/lodash.js:499:17)
2017-04-27T09:28:41.166749+00:00 app[web.1]:     at wrapper (/app/node_modules/lodash/lodash.js:5356:16)
2017-04-27T09:28:41.166749+00:00 app[web.1]:     at Request.handleRequestTranportRes (/app/node_modules/@slack/client/lib/clients/transports/request.js:20:5)
2017-04-27T09:28:41.166750+00:00 app[web.1]:     at apply (/app/node_modules/lodash/lodash.js:499:17)
2017-04-27T09:28:41.166750+00:00 app[web.1]:     at Request.wrapper [as _callback] (/app/node_modules/lodash/lodash.js:5356:16)
2017-04-27T09:28:41.166751+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/request/request.js:188:22)
2017-04-27T09:28:41.166751+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2017-04-27T09:28:41.166752+00:00 app[web.1]:     at Request.emit (events.js:191:7)
2017-04-27T09:28:41.166752+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/request/request.js:1171:10)
2017-04-27T09:28:41.166753+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-04-27T09:28:41.166753+00:00 app[web.1]:     at Request.emit (events.js:188:7)
2017-04-27T09:28:41.166753+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1091:12)
2017-04-27T09:28:41.166754+00:00 app[web.1]:     at IncomingMessage.g (events.js:291:16)
2017-04-27T09:28:41.166754+00:00 app[web.1]:     at emitNone (events.js:91:20)
2017-04-27T09:28:41.166755+00:00 app[web.1]:     at IncomingMessage.emit (events.js:185:7)
```

**Comment by aoberoi** [comment]
looks like your parameters might be mixed up. try something like:

```
slack.chat.unfurl(message_ts, channel, {
      [link.url]: { text: "blah" }
    }, (err, info) => {
      if (err)
        throw new Error(err)
      console.log(info)
    });
```

note: token isn't an parameter. since you instantiate the `WebClient` with it, its not necessary to pass in again.

**Comment by matthewdias** [comment]
ah ok. i will try that. I wasn't sure of the parameter order, as I was going off of [the docs](https://api.slack.com/methods/chat.unfurl). is there a different place i can reference to see the proper order?

Also the unfurling guide gives the following description for the token param:
>`token` - the user token granted to you when installing your app for the team you're acting on behalf of.

Does this mean i need to instantiate the `WebClient` with that same token i got from auth? I was under the impression that I was supposed to pass my slack api token there.

**Comment by aoberoi** [comment]
unfortunately, the docs on this library are not as clear as they can be.

in general, the `WebClient` instance holds onto the token so that each time you use it, you don't need to pass it in explicitly. the parameters for any Web API method are those that are listed as required in the docs, and then an object hash containing any parameters that are optional. there are a few exceptions, but they are pretty rare.

glad we figured this out!
