### ISSUE TITLE
files.info command crashing node

### ISSUE THREAD

**Issue by tijs** [slackapi/node-slack-sdk#353]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

I'm trying to retrieve file info for a specific file ID using the file.info command in the WebClient. While this worked at some point my bit now crashes when i do this (for any image/file) returning the TypeError "source.on is not a function"

#### Reproducible in:
node-slack-sdk version: 3.9.0
OS version(s): Mac OS 10.12
Device(s): Mac

#### Steps to reproduce:

1. install the WebClient
2. get a file ID (for a file that exists in the team for which the bot has access)
3. run the web.files.info() command for the given file:

```
web.files.info(
          {
            file: message.item.file,
            count: 1,
            page: 1
          },
          function(err, info) {
            console.log("file", err, info);
          }
);
```

### Expected result:

an object containing the file info such ads the download url and file name

### Actual result:

A TypeError:

```
/Users/tijs/Projects/bunka-bot/node_modules/delayed-stream/lib/delayed_stream.js:33
  source.on('error', function() {});
         ^

TypeError: source.on is not a function
    at Function.DelayedStream.create (/Users/tijs/Projects/bunka-bot/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/Users/tijs/Projects/bunka-bot/node_modules/combined-stream/lib/combined_stream.js:43:37)
    at FormData.append (/Users/tijs/Projects/bunka-bot/node_modules/form-data/lib/form_data.js:68:3)
    at appendFormValue (/Users/tijs/Projects/bunka-bot/node_modules/request/request.js:326:21)
    at Request.init (/Users/tijs/Projects/bunka-bot/node_modules/request/request.js:337:11)
    at new Request (/Users/tijs/Projects/bunka-bot/node_modules/request/request.js:130:8)
    at request (/Users/tijs/Projects/bunka-bot/node_modules/request/index.js:54:10)
    at Function.post (/Users/tijs/Projects/bunka-bot/node_modules/request/index.js:62:12)
    at WebAPIClient.requestTransport [as transport] (/Users/tijs/Projects/bunka-bot/node_modules/@slack/client/lib/clients/transports/request.js:56:11)
    at RetryOperation.attemptTransportCall [as _fn] (/Users/tijs/Projects/bunka-bot/node_modules/@slack/client/lib/clients/client.js:121:11)
    at RetryOperation.attempt (/Users/tijs/Projects/bunka-bot/node_modules/retry/lib/retry_operation.js:88:8)
    at WebAPIClient._callTransport (/Users/tijs/Projects/bunka-bot/node_modules/@slack/client/lib/clients/client.js:120:11)
    at wrapper (/Users/tijs/Projects/bunka-bot/node_modules/lodash/lodash.js:4968:19)
    at /Users/tijs/Projects/bunka-bot/node_modules/@slack/client/node_modules/async/lib/async.js:987:13
    at Immediate.process (/Users/tijs/Projects/bunka-bot/node_modules/@slack/client/node_modules/async/lib/async.js:953:21)
    at runCallback (timers.js:651:20)

```

**Comment by tijs** [comment]
ok never mind. the file ID is required so it should be a separate argument not part of the object with extra arguments. 

really not a fan of this api design btw but to each his own :)
