### ISSUE TITLE
reactions.get Facet fails to send request when requesting "full: true" and "file: id"

### ISSUE THREAD

**Issue by shawnpetros** [slackapi/node-slack-sdk#452]
### Description

When trying to invoke ReactionFacet `reactions.get()` method passing an object with `file: id, full: true` properties, the request fails in a strange way. It appears to create a malformed request and actually fails prior to sending the request outside of the SDK code (apparently?). When removing the `full: true` property the request is made and responds as expect with either the discovered file, or a `{ "ok": false, "error": "file_not_found" }`. Adding back the `full: true` property to the object results in the request never taking place for some reason.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 3.15.0

node version: 8.9.0

OS version(s): macOS 10.13.2

#### Steps to reproduce:

1. Create simple app that imports `WebClient` from `@slack/client` module
2. New up `WebClient` with a `TOKEN`
3. Fire `web.reactions.get({ file: "any_string", full: true })` and view stack trace error

#### Expected result:

Return an instance of file object for a found match, or return 

```json
{
  "ok": false,
  "error": "file_not_found"
}
```

from Slack API.

#### Actual result:

Instead, the request fails before being sent, with the following stack trace:

```bash
_http_outgoing.js:640
    throw new TypeError('First argument must be a string or Buffer');
    ^
TypeError: First argument must be a string or Buffer
    at write_ (_http_outgoing.js:640:11)
    at ClientRequest.write (_http_outgoing.js:615:10)
    at Request.write (/path/to/thing/node_modules/request/request.js:1399:27)
    at FormData.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:115:13)
    at FormData.emit (events.js:210:7)
    at FormData.CombinedStream.write (/path/to/thing/node_modules/combined-stream/lib/combined_stream.js:118:8)
    at FormData.CombinedStream._pipeNext (/path/to/thing/node_modules/combined-stream/lib/combined_stream.js:106:8)
    at FormData.CombinedStream._getNext (/path/to/thing/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (/path/to/thing/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.CombinedStream._getNext (/path/to/thing/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (/path/to/thing/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.<anonymous> (/path/to/thing/node_modules/combined-stream/lib/combined_stream.js:91:10)
    at FormData.<anonymous> (/path/to/thing/node_modules/form-data/lib/form_data.js:273:5)
    at FormData.CombinedStream._getNext (/path/to/thing/node_modules/combined-stream/lib/combined_stream.js:84:3)
    at FormData.CombinedStream._pipeNext (/path/to/thing/node_modules/combined-stream/lib/combined_stream.js:107:8)
```

#### Attachments:

Sample app to reproduce:

```javascript
const { SLACK_TOKEN } = process.env;
const { WebClient } = require('@slack/client');

const web = new WebClient(SLACK_TOKEN);

web.reactions.get({ file: 'STRING', full: true });
```

**Comment by shawnpetros** [comment]
Any update on this?

**Comment by Roach** [comment]
@shawnpetros do you get the same result if you pass true as a string `full: 'true'` instead of a bool?

**Comment by shawnpetros** [comment]
Honestly, I hadn’t thought to try that yet, when I get back to my computer I’ll try it.

Cheers!

Shawn Petros
DevOps Engineer
Northwestern Mutual

**Comment by aoberoi** [comment]
thanks for digging into this @clavin! it seems like we have a reasonable workaround for v3, so i'm hoping to land a fix for this in v4. it unfortunately uses the same trick to coerce the body to multi-part content type. maybe we can come up with something better.

my proposal is to just special case the method name `files.upload`. this feels sloppy to me because i'd like the `apiCall()` method to stay as generic as possible. the risk is that someday there may be another method that accepts files in the same shape of arguments as `files.upload` and then we have to grow the list of special cases. but still, i can't think of anything better.
