### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by nxz91** [slackapi/node-slack-sdk#498]
### Description

When simply requiring `@slack/client`, I get this error:
```
TypeError: Cannot read property 'replace' of undefined
    at replaceSlashes (/Users/abc/abc/abc/slack/node_modules/@slack/client/dist/util.js:17:13)
    at Object.<anonymous> (/Users/abc/abc/abc/slack/node_modules/@slack/client/dist/util.js:19:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/abc/abc/abc/slack/node_modules/@slack/client/dist/logger.js:4:16)
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.0.0

node version: 8.9.0 (LTS)

OS version(s): macOS 10.13.3 (High Sierra)

#### Steps to reproduce:

1. yarn add @slack/client
2. create and run new script with only "const Slack = require('@slack/client')" or type the same in the node REPL
3. boom

#### Expected result:

it works

#### Actual result:

it breaks

### Attachment

http://gph.is/2p7Yezw

**Comment by aoberoi** [comment]
@nxz91 thanks for reporting. are you in a package that either doesn't have a `package.json`, or the `package.json` lacks a `"name"` or `"version"` property? If so, this is probably a duplicate of #478

**Comment by nxz91** [comment]
@aoberoi you were right, didn't see that one 🙈
