### ISSUE TITLE
sendMessage is returning invalid channel ID when given the proper ID

### ISSUE THREAD

**Issue by twiclo** [slackapi/node-slack-sdk#510]
### Description

I've confirmed that the user ID is correct yet when I try to use sendMessage it doesn't work. This is the first time I've run into this issue. sendMessage hasn't given me problems before. I logged out the message on a received message and the user ID matches the same user I'm searching for with `web.users.list()`.
Logs show the ID is U3AQL2KS6. I've tried sending a message just passing the ID as a string and having it be a return from `getUserId`. Neither work. I get the below error and the error is the same for both sending attempts.

```
Unhandled rejection SlackRTMError: invalid channel id
    at RTMClient.handleMessageAck [as _handleMessageAck] (/home/twiclo/Projects/hostbot/node_modules/@slack/client/lib/clients/rtm/client.js:513:40)
    at RTMClient._handleWsMessageViaEventHandler (/home/twiclo/Projects/hostbot/node_modules/@slack/client/lib/clients/rtm/client.js:476:12)
    at RTMClient.handleWsMessage (/home/twiclo/Projects/hostbot/node_modules/@slack/client/lib/clients/rtm/client.js:436:10)
    at WebSocket.wrapper (/home/twiclo/Projects/hostbot/node_modules/lodash/lodash.js:4941:19)
    at WebSocket.emit (events.js:160:13)
    at Receiver.ontext (/home/twiclo/Projects/hostbot/node_modules/ws/lib/WebSocket.js:841:10)
    at /home/twiclo/Projects/hostbot/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/home/twiclo/Projects/hostbot/node_modules/ws/lib/Receiver.js:371:5)
    at /home/twiclo/Projects/hostbot/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/home/twiclo/Projects/hostbot/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/home/twiclo/Projects/hostbot/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/home/twiclo/Projects/hostbot/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/home/twiclo/Projects/hostbot/node_modules/ws/lib/Receiver.js:103:24)
    at TLSSocket.realHandler (/home/twiclo/Projects/hostbot/node_modules/ws/lib/WebSocket.js:825:20)
    at TLSSocket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
```

```
async function getUserId(user) {
    for(let member of (await web.users.list()).members) {
        if(member.name == user) {
        console.log(member.id) //U3AQL2KS6
            return member.id
        }
    }   
}

rtm.on(slack.RTM_EVENTS.MESSAGE, async message => {
    if(message.file && message.file.filetype == 'email') {
        var fileObject  = message.file.attachments[0]
        console.log(`Generating new array from ${fileObject.filename}`)
        console.log(await getUserId("tanner_wilcox"))
        rtm.sendMessage(`Generating new array from ${fileObject.filename}`, (await getUserId("tanner_wilcox")))
        rtm.sendMessage(`Generating new array from ${fileObject.filename}`, 'D6Q7RM3L1')
    }
}
```
Sorry if I'm missing something but this just seems like a straight bug to me. Thanks!

### What type of issue is this?
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
while i was able to reproduce this, this actually is the expected behavior. you're sending a message with the channel set to a user ID (Uxxxxxx). the docs say the following:

> You can send a message to a private group or direct message channel in the same way, but using a Group ID (C024BE91L) or DM channel ID (D024BE91L).

so what you'll need to do is invoke `web.im.open()` to get a DM channel ID.

```javascript
async function getUserId(user) {
    for(let member of (await web.users.list()).members) {
        if(member.name == user) {
            return (await web.im.open(member.id)).channel.id
        }
    }   
}
```

**Comment by twiclo** [comment]
My mistake. Thanks for pointing that out.
