### ISSUE TITLE
web.chat.postMessage returns invalid_array_arg when following the examples

### ISSUE THREAD

**Issue by twiclo** [slackapi/node-slack-sdk#525]
https://github.com/slackapi/node-slack-sdk#posting-a-message-with-web-api

When following the example provided at the above URL the api responds with the below error. I did a straight copy and paste from the example into a temp file and ran it (after putting my token and a proper channel ID in). This is the error I got

> Error: invalid_array_arg
    at handleHttpResponse (/home/twiclo/Projects/hostbot/node_modules/@slack/client/lib/clients/transports/call-transport.js:103:17)
    at handleTransportResponse (/home/twiclo/Projects/hostbot/node_modules/@slack/client/lib/clients/transports/call-transport.js:153:19)
    at apply (/home/twiclo/Projects/hostbot/node_modules/lodash/lodash.js:470:17)
    at wrapper (/home/twiclo/Projects/hostbot/node_modules/lodash/lodash.js:5329:16)
    at Request.handleRequestTranportRes (/home/twiclo/Projects/hostbot/node_modules/@slack/client/lib/clients/transports/request.js:21:5)
    at apply (/home/twiclo/Projects/hostbot/node_modules/lodash/lodash.js:470:17)
    at Request.wrapper [as _callback] (/home/twiclo/Projects/hostbot/node_modules/lodash/lodash.js:5329:16)
    at Request.self.callback (/home/twiclo/Projects/hostbot/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/home/twiclo/Projects/hostbot/node_modules/request/request.js:1060:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/home/twiclo/Projects/hostbot/node_modules/request/request.js:980:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)

There's definitely a chance I'm providing the wrong chatID. I'm passing in "D8JQ7Q6V9" which is the DM ID with me and the bot user

**Comment by aoberoi** [comment]
@twiclo from the stack trace, it looks like your using v3 of this package, and the docs have been updated to v4 - see the [migration guide](https://github.com/slackapi/node-slack-sdk/wiki/Migration-Guide-for-v4) for differences. 

Unfortunately, we don’t have the older v3 docs hosted anywhere, but we have an issue open to track this. #486

**Comment by twiclo** [comment]
[twiclo@localhost hostbot]$ npm @slack/client --version
5.6.0

Is that version different than what I should be running? How do I check the real version to make sure I'm good?

**Comment by aoberoi** [comment]
Oh sorry for the confusion. That’s your version of NPM. I meant the version of the `@slack/client` package, which is usually specified in your `package.json` file under the key `dependencies`.

If you just want to upgrade to the latest you could just run `npm install @slack/client@4`. It should handle updating your `package.json` as well.

**Comment by twiclo** [comment]
Okay thanks for the help
