### ISSUE TITLE
TypeError: Cannot read property 'aborted' of null

### ISSUE THREAD

**Issue by zcbenz** [slackapi/node-slack-sdk#552]
### Description

After losing connection for a very long time (> 2 hours), the RTMClient would throw following exception and will never recover:

```
[ERROR] @slack/client:RTMClient A websocket error occurred: connect ETIMEDOUT 13.115.224.139:443
{ Error: Failed to send message on websocket: connect ETIMEDOUT 13.115.224.139:443
    at websocketErrorWithOriginal (/Users/zcbenz/codes/wey/node_modules/@slack/client/dist/RTMClient.js:467:42)
    at WebSocket.websocket.addEventListener (/Users/zcbenz/codes/wey/node_modules/@slack/client/dist/RTMClient.js:394:32)
    at WebSocket.onError (/Users/zcbenz/codes/wey/node_modules/ws/lib/event-target.js:128:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at WebSocket.finalize (/Users/zcbenz/codes/wey/node_modules/ws/lib/websocket.js:185:12)
    at ClientRequest._req.on (/Users/zcbenz/codes/wey/node_modules/ws/lib/websocket.js:635:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
  code: 'slackclient_rtmclient_websocket_error',
  original: 
   { Error: connect ETIMEDOUT 13.115.224.139:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '13.115.224.139',
     port: 443 } }
Error: Unhandled event 'websocket close' in state 'connecting'.
    at StateMachine.handleUnhandledEvent (/Users/zcbenz/codes/wey/node_modules/finity/lib/core/StateMachine.js:76:13)
    at /Users/zcbenz/codes/wey/node_modules/finity/lib/core/HierarchicalStateMachine.js:79:33
    at TaskScheduler.execute (/Users/zcbenz/codes/wey/node_modules/finity/lib/core/TaskScheduler.js:29:7)
    at TaskScheduler.enqueue (/Users/zcbenz/codes/wey/node_modules/finity/lib/core/TaskScheduler.js:19:12)
    at HierarchicalStateMachine.handle (/Users/zcbenz/codes/wey/node_modules/finity/lib/core/HierarchicalStateMachine.js:72:24)
    at WebSocket.websocket.addEventListener.event (/Users/zcbenz/codes/wey/node_modules/@slack/client/dist/RTMClient.js:391:77)
    at WebSocket.onClose (/Users/zcbenz/codes/wey/node_modules/ws/lib/event-target.js:124:16)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.finalize (/Users/zcbenz/codes/wey/node_modules/ws/lib/websocket.js:187:12)
TypeError: Cannot read property 'aborted' of null
    at ClientRequest._req.on (/Users/zcbenz/codes/wey/node_modules/ws/lib/websocket.js:632:19)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketCloseListener (_http_client.js:363:9)
    at emitOne (events.js:121:20)
    at TLSSocket.emit (events.js:211:7)
    at _handle.close (net.js:554:12)
    at TCP.done [as _onclose] (_tls_wrap.js:356:7)
```

This looks very similar to https://github.com/slackapi/node-slack-sdk/issues/531, except that I got a `TypeError: Cannot read property 'aborted' of null` at the end. I have updated to 4.2.0.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.2.0

node version: 8.10.0

OS version(s): macOS 10.12

#### Steps to reproduce:

1. Start an RTMClient
2. Close the laptop for more than 2 hours
3. Open the laptop

#### Expected result:

The RTMClient should be in the `disconnected` or `connecting` state, and then transferred to the `connected` state later.

#### Actual result:

The RTMClient is always in the `connecting` state.

#### Attachments:

I don't have a minimal project to reproduce this, you can checkout and run https://github.com/yue/wey to reproduce this.

**Comment by aoberoi** [comment]
thanks for the report and the stacktrace @zcbenz! i'm fairly confident that this is actually the same issue as #531, so i'm going to consolidate by closing this as a duplicate.

i'm working on a fix now and hopefully we can release that before the end of the week.
