### ISSUE TITLE
State Machine Error: Unhandled event 'explicit disconnect' in state 'connecting'

### ISSUE THREAD

**Issue by bmajz** [slackapi/node-slack-sdk#595]
### Description

Unhandled event 'explicit disconnect' in state 'connecting'.  In this case, we explicitly attempted to kill the RTM client using `rtm.disconnect()`

EXPECTED: Smooth transition, or an error message
ACTUAL: Unhandled exception

Call stack:
Error: Unhandled event 'explicit disconnect' in state 'connecting'.
     at StateMachine.handleUnhandledEvent (/home/node_modules/finity/lib/core/StateMachine.js:76:13)
     at /home/node_modules/finity/lib/core/HierarchicalStateMachine.js:79:33
    at TaskScheduler.execute (/home/node_modules/finity/lib/core/TaskScheduler.js:29:7)
     at TaskScheduler.enqueue (/home/node_modules/finity/lib/core/TaskScheduler.js:19:12)
     at HierarchicalStateMachine.handle (/home/node_modules/finity/lib/core     at RTMClient.disconnect (/home/node_modules/@slack/client/dist/RTMClient.js:272:27)
     at killRealtimeListener (/home/rtm.js:255:21)
     at /home/rtm.js:169:25
     at step (/home/rtm.js:32:23)
     at Object.next (/home/rtm.js:13:53) 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.3.1

node version: 8.11.3

OS version(s): Alpine Linux

**Comment by aoberoi** [comment]
This sounds like a sup of #576

**Comment by bmajz** [comment]
Indeed it does!
