### ISSUE TITLE
postMessage API Error

### ISSUE THREAD

**Issue by andersoncsantos** [slackapi/node-slack-sdk#843]
Sometimes message is not posted and returns this:
```
(node:38992) UnhandledPromiseRejectionWarning: Error: An API error occurred: api_method_did_not_exit
    at Object.platformErrorFromResult (I:\Processos\Slack\zabbix-slack\node_modules\@slack\web-api\dist\errors.js:50:33)
    at WebClient.apiCall (I:\Processos\Slack\zabbix-slack\node_modules\@slack\web-api\dist\WebClient.js:374:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:38992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.
```

**Comment by clavin** [comment]
How often do you get this error? Could you share a code snippet that causes this error?

**Comment by andersoncsantos** [comment]
Has occurred frequently in recent days.

Code:

```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
process.env.GLOBAL_AGENT_HTTP_PROXY = 'my_proxy';

const {bootstrap} = require('global-agent');
bootstrap();

const { WebClient } = require('@slack/web-api');

const formating_date = require('./function_date');
const formating_date_hour = require('./function_date_hour');

function addReactions() {

  const mysql = require('mysql');
  const connection = mysql.createConnection({
    host: 'my_host',
    user: 'my_user',
    password: 'my_password',
    database: 'my_db'
  });

  connection.connect();

  const query =
    `SELECT c.name AS HOST, REPLACE(a.subject, 'PROBLEM: ', '') AS PROBLEM, d.severity AS SEVERITY, MAX(a.clock) AS OCCURRENCE, MAX(b.clock) AS CLEAR FROM alerts a
    INNER JOIN alerts b ON b.subject NOT LIKE '%PROBLEM%' AND b.subject LIKE CONCAT('%', REPLACE(a.subject, 'PROBLEM: ', ''), '%')
    INNER JOIN hosts c ON a.message LIKE CONCAT('%', c.host, '%')
    INNER JOIN events d ON a.subject LIKE CONCAT('%', d.name, '%')
    WHERE (SELECT MAX(b.clock)) BETWEEN (SELECT UNIX_TIMESTAMP()) - (96) AND (SELECT UNIX_TIMESTAMP())
    AND a.subject NOT LIKE '%RECOVERY%'
    AND d.severity != 0
    AND (SELECT MAX(b.clock) > MAX(a.clock))
    AND (SELECT MAX(a.clock) > (SELECT MAX(b.clock) - 604800))
    GROUP BY c.name, a.subject, b.subject, d.severity
    ORDER BY OCCURRENCE`;

  // wait 1s
  start = new Date().getTime() + 3000;
  while (true) {
    if (new Date().getTime() >= start) {
      break;
    }
  }


  connection.query(query, function (error, results, fields) {
    //if (error) throw error;
    //console.log('', results[0].message);

    // let size = 0;
    // if (results.length > 19 ? size = 19 : size = results.length);

    try {
      for (let i = 0, len = results.length; i < len; i++) {

        vr = results.length;

        let occurrence = "";
        occurrence = formating_date_hour(results[i].OCCURRENCE * 1000);

        let occurr_search = "";
        occurr_search = formating_date(results[i].OCCURRENCE * 1000);

        let clear = "";
        clear = formating_date_hour(results[i].CLEAR * 1000);

        let host = "";
        host = results[i].HOST;

        let summary = "";
        summary = results[i].PROBLEM;
        summary = summary.replace('PROBLEM: ', '');
        summary = summary.replace(host + ' ', '');

        let severity = ""; // red: #e74c3c; yellow: #ffeb3b; green: #2ecc71; orange: #f39c12; blue: #3498db // black: #000000
        severity = results[i].SEVERITY;

        let severity_desc = "";

        if (severity === 2) { severity_desc = 'Warning'; };
        if (severity === 3) { severity_desc = 'Average'; };
        if (severity === 4) { severity_desc = 'High'; };
        if (severity === 5) { severity_desc = 'Disaster'; };

        console.log(host, ' ', occurrence);

        let texto = ""
        texto =
          '_*host:* '
          + host + '_'
          + '\n'
          + '_'
          + '*problem name:* '
          + summary + '_'
          + '\n'
          + '_'
          + '*severity:* '
          + severity_desc + '_'
          + '\n'
          + '_'
          + '*occurrence:* '
          + occurrence + '_'
          + '\n'
          + '_'
          + '*clear:* '
          + clear + '_';

        const web = new WebClient('my_access_key');

        (async () => {
          let msgs = await web.search.messages({
            query: 'in:#oss_infra ' + host + ' ' + summary + ' ' + occurrence
          });

          let msg = "";
          let msg_t = "";
          let msg_t2 = "";
          //let texto = "";

          let in_msg = msgs['messages'];
          let chars = in_msg['matches'];
          for (let i = 0, len = chars.length; i < len; i++) {
            msg = chars[i];
            msg_t = msg['attachments'];
            //msg_t2 = msg_t[0];

            console.log(msg.ts);
            //texto = msg_t2.text;

            const web = new WebClient('my_access_key');

            try {
              await web.chat.update({
                channel: 'CKGPH2065', //CJP48RVGE //C9E03H9L7 //CKGPH2065
                attachments: [
                  {
                    "color": '#2ecc71',
                    "mrkdwn_in": ["text"],
                    "text": texto,
                    "ts": Math.floor(new Date().getTime() / 1000.0)
                  }
                ],
                ts: msg.ts
              });

              // await web.reactions.add({
              //   channel: 'CKGPH2065',
              //   name: 'heavy_check_mark',
              //   timestamp: msg.ts,
              // });

            } catch (error) {
              console.log('message not found');
            }
          }
        }

        )();

        // wait 1s
        start = new Date().getTime() + 3000;
        while (true) {
          if (new Date().getTime() >= start) {
            break;
          }
        }
      }
    } catch (error) {
      console.log('connection failed', error);
      //connection.end();
    }
  });

  connection.end();
}

//addReactions();

module.exports = addReactions

```

**Comment by clavin** [comment]
This was a temporary issue on our end and should have already been fixed since. Let me know if you're still encountering this. Thanks for the notice!
