### ISSUE TITLE
Post Message Error

### ISSUE THREAD

**Issue by andersoncsantos** [slackapi/node-slack-sdk#859]
Hi, I'm receiving this error from API:

````
[WARN]  WebClient:1144 http request failed read ECONNRESET
[WARN]  WebClient:674 http request failed read ECONNRESET
[WARN]  WebClient:1243 http request failed read ECONNRESET
[WARN]  WebClient:480 http request failed read ECONNRESET
[WARN]  WebClient:625 http request failed read ECONNRESET
[WARN]  WebClient:683 http request failed read ECONNRESET
[WARN]  WebClient:805 http request failed read ECONNRESET
[WARN]  WebClient:372 http request failed read ECONNRESET
[WARN]  WebClient:722 http request failed read ECONNRESET
[WARN]  WebClient:1104 http request failed read ECONNRESET
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
````
My code:

````
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
process.env.GLOBAL_AGENT_HTTP_PROXY = 'http://10.64.227.214:5865';

const {bootstrap} = require('global-agent');
bootstrap();

const { WebClient } = require('@slack/web-api');

const formating_date = require('./function_date');
const formating_date_hour = require('./function_date_hour');

function addReactions() {

  const mysql = require('mysql');
  const connection = mysql.createConnection({
    host: 'host',
    user: 'user',
    password: 'password',
    database: 'database'
  });

  connection.connect();

  const query =
    `SELECT c.name AS HOST, REPLACE(a.subject, 'PROBLEM: ', '') AS PROBLEM, d.severity AS SEVERITY, a.clock AS OCCURRENCE, b.clock AS CLEAR FROM alerts a
    INNER JOIN alerts b ON b.subject NOT LIKE '%PROBLEM%' AND b.subject LIKE CONCAT('%', REPLACE(a.subject, 'PROBLEM: ', ''), '%')
    INNER JOIN hosts c ON a.message LIKE CONCAT('%', c.host, '%')
    INNER JOIN events d ON a.subject LIKE CONCAT('%', d.name, '%')
    WHERE (SELECT MAX(b.clock)) BETWEEN (SELECT UNIX_TIMESTAMP()) - (3600 * 24) AND (SELECT UNIX_TIMESTAMP())
    AND a.subject NOT LIKE '%RECOVERY%'
    AND d.severity != 0
    AND (SELECT MAX(b.clock) > MAX(a.clock))
    GROUP BY c.name, a.subject, b.subject, d.severity, a.clock, b.clock
    ORDER BY OCCURRENCE`;

  // wait 1s
  start = new Date().getTime() + 3000;
  while (true) {
    if (new Date().getTime() >= start) {
      break;
    }
  }


  connection.query(query, function (error, results, fields) {
    //if (error) throw error;
    //console.log('', results[0].message);

    // let size = 0;
    // if (results.length > 19 ? size = 19 : size = results.length);

    try {
      for (let i = 0, len = results.length; i < len; i++) {

        let canal = "";
        canal = "CKGPH2065"

        let canal_search = "";
        canal_search = "in:#oss_infra ";

        let occurrence = "";
        occurrence = formating_date_hour(results[i].OCCURRENCE * 1000);

        /* let occurr_search = "";
        occurr_search = formating_date(results[i].OCCURRENCE * 1000); */

        let clear = "";
        clear = formating_date_hour(results[i].CLEAR * 1000);

        let host = "";
        host = results[i].HOST;

        let summary = "";
        summary = results[i].PROBLEM;
        summary = summary.replace('PROBLEM: ', '');
        summary = summary.replace(host + ' ', '');

        let severity = ""; // red: #e74c3c; yellow: #ffeb3b; green: #2ecc71; orange: #f39c12; blue: #3498db // black: #000000
        severity = results[i].SEVERITY;

        let severity_desc = "";

        if (severity === 2) { severity_desc = 'Warning'; };
        if (severity === 3) { severity_desc = 'Average'; };
        if (severity === 4) { severity_desc = 'High'; };
        if (severity === 5) { severity_desc = 'Disaster'; };

        if (host.includes('VGPRIP01')
          || host.includes('VGQDS01')
          || host.includes('VGPRIP02')
          || host.includes('VGIPPRC02')
          || host.includes('VGIPPRC02')
          || host.includes('VGPTTDEC01')
          || host.includes('VGWEB01')
          || host.includes('VGIPCON01')
          || host.includes('VGIPDEC01')
          || host.includes('VGIPPRC01')
          || host.includes('VGITC01')
          || host.includes('VGAPP01')) {
          color = '#e74c3c';
          severity_desc = 'High';
        };

        if (summary.includes('Disk space is low')) {
          color = '#e74c3c';
          severity_desc = 'High';
        };

        if (summary.includes('Disk space is critically low')) {
          color = '#000000';
          severity_desc = 'Disaster';
        };

        if (host.includes('Mobileum')
          || host.includes('SG7000')) {
          canal = "CK178DM0V";
          canal_search = "in:#corecs_notification ";
        };

        //console.log(host, ' ', occurrence);

        let texto = ""
        texto =
          '_*host:* '
          + host + '_'
          + '\n'
          + '_'
          + '*problem name:* '
          + summary + '_'
          + '\n'
          + '_'
          + '*severity:* '
          + severity_desc + '_'
          + '\n'
          + '_'
          + '*occurrence:* '
          + occurrence + '_'
          + '\n'
          + '_'
          + '*clear:* '
          + clear + '_';

        console.log('"' + summary + '"' + ' ' + occurrence + ' -clear');

        const web = new WebClient('my key');

        (async () => {
          let msgs = await web.search.messages({
            query: canal_search + '"' + summary + '"' + ' ' + occurrence + ' -clear'
          });

          let msg = "";
          let msg_t = "";
          let msg_t2 = "";
          //let texto = "";

          let in_msg = msgs['messages'];
          let chars = in_msg['matches'];
          for (let i = 0, len = chars.length; i < len; i++) {
            msg = chars[i];
            msg_t = msg['attachments'];
            //msg_t2 = msg_t[0];

            console.log('"' + summary + '"' + ' ' + occurrence);
            console.log(msg.ts);
            //texto = msg_t2.text;

            const web = new WebClient('my key');
            try {
              await web.chat.update({
                channel: canal, //CJP48RVGE //C9E03H9L7 //CKGPH2065
                attachments: [
                  {
                    "color": '#2ecc71',
                    "mrkdwn_in": ["text"],
                    "text": texto,
                    "ts": Math.floor(new Date().getTime() / 1000.0)
                  }
                ],
                ts: msg.ts
              });

              // await web.reactions.add({
              //   channel: 'CKGPH2065',
              //   name: 'heavy_check_mark',
              //   timestamp: msg.ts,
              // });

            } catch (error) {
              console.log('message not found');
            }
          }
        }

        )();

        // wait 1s
        start = new Date().getTime() + 3000;
        while (true) {
          if (new Date().getTime() >= start) {
            break;
          }
        }
      }
    } catch (error) {
      console.log('connection failed', error);
      //connection.end();
    }
  });

  connection.end();
}

//addReactions();

module.exports = addReactions
````

**Comment by codewithbugs01** [comment]
Why was this issue closed?

**Comment by hello-ashleyintech** [comment]
Hi, @codewithbugs01! This issue was likely closed either due to inactivity or the original poster finding a solution to their issue. If you are running into an issue with the Node SDK, please submit an issue for it [here](https://github.com/slackapi/node-slack-sdk/issues/new/choose) and provide some info on it and I'd be happy to help you figure it out! 😄
