### ISSUE TITLE
@slack/interactive-messages fails to process button pressed in a message

### ISSUE THREAD

**Issue by uluaiv** [slackapi/node-slack-sdk#934]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 1.4.0

node version: v12.13.0

OS version(s): Linux Ubuntu 16.04

#### Steps to reproduce:

1. Send an user a message with this blocks:

```[
  {
    "type": "section",
    "text": {
      "type": "mrkdwn",
      "text": "The results of your search are now available"
    },
    "accessory": {
      "type": "button",
      "text": {
        "type": "plain_text",
        "text": "Show my options",
        "emoji": true
      },
      "value": "{searchId}",
      "action_id": "show_search_results"
    }
  }
]
```

2. Pressing the button will produce a payload of this kind:

```
{
  "type": "block_actions",
  "team": {
    "id": "************",
    "domain": "************"
  },
  "user": {
    "id": "************",
    "username": "************",
    "name": "************",
    "team_id": "************"
  },
  "api_app_id": "************",
  "token": "************",
  "container": {
    "type": "message",
    "message_ts": "************",
    "channel_id": "************",
    "is_ephemeral": false
  },
  "trigger_id": "************",
  "channel": {
    "id": "************",
    "name": "directmessage"
  },
  "message": {
    "type": "message",
    "subtype": "bot_message",
    "text": "This+content+can't+be+displayed.",
    "ts": "************",
    "username": "************",
    "bot_id": "************",
    "blocks": [
      {
        "type": "section",
        "block_id": "4Kzy+",
        "text": {
          "type": "mrkdwn",
          "text": "The+results+of+your+search+are+now+available",
          "verbatim": false
        },
        "accessory": {
          "type": "button",
          "action_id": "show-available-options",
          "text": {
            "type": "plain_text",
            "text": "Show+my+options",
            "emoji": true
          },
          "value": "0"
        }
      }
    ]
  },
  "response_url": "https:\/\/hooks.slack.com\/************",
  "actions": [
    {
      "action_id": "show-available-options",
      "block_id": "4Kzy+",
      "text": {
        "type": "plain_text",
        "text": "Show+my+options",
        "emoji": true
      },
      "value": "0",
      "type": "button",
      "action_ts": "************"
    }
  ]
}
```

3. The handler of this action (show-available-options) is not called. Thorough debugging shows that the dispatching process causes an exception in the matchCallback method of adapter.ts (search for SlackMessageAdapter.prototype.matchCallback = function, currently line 418).

4. Wrapping the code inside this.callbacks.find with a try-catch that returns false in case of exception solves the issue.

#### Expected result:

The action handler specified by me for this payload should have been called

#### Actual result:

The payload was processed as valid but was not dispatched to the right handler because of a silent internal exception

#### Attachments:

You can see from the log, the last message printed is "request signing verification success". After that the dispatching process fails.

```
Thu, 19 Dec 2019 10:33:13 GMT express:router dispatching POST /slack/interactions
Thu, 19 Dec 2019 10:33:13 GMT express:router query  : /slack/interactions
Thu, 19 Dec 2019 10:33:13 GMT express:router expressInit  : /slack/interactions
Thu, 19 Dec 2019 10:33:13 GMT express:router initialize  : /slack/interactions
Thu, 19 Dec 2019 10:33:13 GMT express:router trim prefix (/slack/interactions) from url /slack/interactions
Thu, 19 Dec 2019 10:33:13 GMT express:router <anonymous> /slack/interactions : /slack/interactions
2019-12-19T10:33:13.791Z @slack/interactive-messages:http-handler request received - method: POST, path: /
2019-12-19T10:33:13.791Z @slack/interactive-messages:http-handler Parsing raw request
2019-12-19T10:33:13.791Z @slack/interactive-messages:http-handler request signing verification success
```

**Comment by aoberoi** [comment]
Hi @uluaiv, thanks for reporting.

I noticed in your reproduction steps, the initial message uses the action ID `"show_search_results"`, but the payload uses `"show-available-options"`. These don't match. What does your action handler (call to `slackInteractions.action()`) look like? Is it possible that the action ID from your message doesn't match the one you used to register the handler?

> Thorough debugging shows that the dispatching process causes an exception in the matchCallback method of adapter.ts (search for SlackMessageAdapter.prototype.matchCallback = function, currently line 418).

This sounds like it could be a bug. Can you provide any more information about the exception? It sounds like you wrapped this and caught the exception. Could you print the error (`console.error(error)`) and share what it shows?

At the very least, I think we should make `SlackMessageAdapter#dispatch()` and async method so that thrown exceptions are not silently ignored, and instead the returned Promise is rejected, which allows the `http-handler` to respond with a status code 500, and the user to see the application had an error.

**Comment by uluaiv** [comment]
Hi @aoberoi,

took some time to get past the Christmas vacation but it's now time to get back to work.
The bug is real: you mentioned some discrepancies between views but they are due to my masking of app related sensitive information.

Here you can find the full stack I can log from the try catch:

```
TypeError: Cannot read property 'callback_id' of undefined
    at /home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/adapter.js:437:96
    at Array.find (<anonymous>)
    at SlackMessageAdapter.matchCallback (/home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/adapter.js:430:31)
    at SlackMessageAdapter.dispatch (/home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/adapter.js:363:29)
    at /home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/http-handler.js:132:46
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
undefined
TypeError: Cannot read property 'callback_id' of undefined
    at /home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/adapter.js:437:96
    at Array.find (<anonymous>)
    at SlackMessageAdapter.matchCallback (/home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/adapter.js:430:31)
    at SlackMessageAdapter.dispatch (/home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/adapter.js:363:29)
    at /home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/http-handler.js:132:46
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
undefined
TypeError: Cannot read property 'callback_id' of undefined
    at /home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/adapter.js:437:96
    at Array.find (<anonymous>)
    at SlackMessageAdapter.matchCallback (/home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/adapter.js:430:31)
    at SlackMessageAdapter.dispatch (/home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/adapter.js:363:29)
    at /home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/http-handler.js:132:46
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
undefined
TypeError: Cannot read property 'callback_id' of undefined
    at /home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/adapter.js:437:96
    at Array.find (<anonymous>)
    at SlackMessageAdapter.matchCallback (/home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/adapter.js:430:31)
    at SlackMessageAdapter.dispatch (/home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/adapter.js:363:29)
    at /home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/http-handler.js:132:46
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
undefined
TypeError: Cannot read property 'callback_id' of undefined
    at /home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/adapter.js:437:96
    at Array.find (<anonymous>)
    at SlackMessageAdapter.matchCallback (/home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/adapter.js:430:31)
    at SlackMessageAdapter.dispatch (/home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/adapter.js:363:29)
    at /home/coingaming/travel-bot-test/node_modules/@slack/interactive-messages/dist/http-handler.js:132:46
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
undefined
```

These two lines of code:

```
                var callbackId = (constraints.handlerType === "view_submission" /* ViewSubmission */ ||
                    constraints.handlerType === "view_closed" /* ViewClosed */) ? payload.view.callback_id : payload.callback_id;
```

Result in a crash because the property callback_id seems not to be present.

This is the action sent from slack to my server upon clicking the button in the message (sensitive details are obfuscated):

```
{
  "type": "block_actions",
  "team": {
    "id": "*********",
    "domain": "*********"
  },
  "user": {
    "id": "*********",
    "username": "*********",
    "name": "*********",
    "team_id": "*********"
  },
  "api_app_id": "*********",
  "token": "*********",
  "container": {
    "type": "message",
    "message_ts": "*********",
    "channel_id": "*********",
    "is_ephemeral": false
  },
  "trigger_id": "*********",
  "channel": {
    "id": "*********",
    "name": "directmessage"
  },
  "message": {
    "bot_id": "*********",
    "type": "message",
    "text": "This content can't be displayed.",
    "user": "*********",
    "ts": "*********",
    "team": ""*********",",
    "blocks": [
      {
        "type": "section",
        "block_id": "WyVM/",
        "text": {
          "type": "mrkdwn",
          "text": "*********",
          "verbatim": false
        },
        "accessory": {
          "type": "button",
          "action_id": "*********",
          "text": {
            "type": "plain_text",
            "text": "Show my options",
            "emoji": true
          },
          "value": "8"
        }
      }
    ]
  },
  "response_url": "*********",
  "actions": [
    {
      "action_id": "*********",
      "block_id": "WyVM/",
      "text": {
        "type": "plain_text",
        "text": "Show my options",
        "emoji": true
      },
      "value": "8",
      "type": "button",
      "action_ts": "*********"
    }
  ]
}
```

**Comment by misscoded** [comment]
We are closing this issue as `@slack/interactive-messages` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
